# This file contains the data structures and scripts necessary to test my genetic
# algorithm on the classic route optimization problem
# 
# This means that both the members of the population will be defined here but generated by the 
# library function. Similarly the fitness function will be written here and passed over
# to the library to do the evaluation